<img src="images\logo_iese.png" width="200" img style="float: right;">

<a id='index'></a>
__Index__

* [Data extraction - csv](#ini)
* [Popular transformations](#transform)
* [SQL like](#sql)

In [ ]:
import pandas as pd
import numpy as np

[Back to index](#index)
<a id='ini'></a>

__Data extraction - csv__

In [ ]:
#https://archive.ics.uci.edu/ml/datasets/census+income
csv_path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'

# Set the column names for the columns in the csv
col_names = [
"age", "workclass", "fnlwgt", "education", "educationnum", "maritalstatus",
"occupation", "relationship", "race", "sex", "capitalgain", "capitalloss",
"hoursperweek", "Country", "over50k"]

# Read the dataset from the provided CSV and print out information about it.
df = pd.read_csv(
        csv_path,                 # Path or URL to the CSV file
        sep=",",                  # Delimiter used in the file (comma-separated values)
        header=None,              # No header row in the file (so pandas won't treat first row as column names)
        names=col_names,          # Assign custom column names
        skipinitialspace=True,    # Ignore spaces immediately after delimiter (e.g., " Private" -> "Private")
        na_values="?",            # Treat '?' as missing values (NaN)
        encoding="utf-8",         # Encoding format of the file
        engine="c"                # Parser engine ('c' is faster; 'python' is more flexible)
    )

target = 'target'

# check data shape
print(df.shape)
df_original = df.copy(deep=True)
df

(32561, 15)

,age,workclass,fnlwgt,education,educationnum,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,Country,over50k
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

__comment__: Regional settings

In [ ]:
del df['race']	
del df['sex']

__comment__: Law | Fairness

In [ ]:
# This step can be used to set a performance baseline 
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
age,32561.0,38.581647,13.640433,17.0,28.0,37.0,48.0,90.0
fnlwgt,32561.0,189778.366512,105549.977697,12285.0,117827.0,178356.0,237051.0,1484705.0
educationnum,32561.0,10.080679,2.572720,1.0,9.0,10.0,12.0,16.0
capitalgain,32561.0,1077.648844,7385.292085,0.0,0.0,0.0,0.0,99999.0
capitalloss,32561.0,87.303830,402.960219,0.0,0.0,0.0,0.0,4356.0
hoursperweek,32561.0,40.437456,12.347429,1.0,40.0,40.0,45.0,99.0

In [ ]:
# check missing data. If missing data, action is need it
df.isna().sum()

age                 0
workclass        1836
fnlwgt              0
education           0
educationnum        0
maritalstatus       0
occupation       1843
relationship        0
capitalgain         0
capitalloss         0
hoursperweek        0
Country           583
over50k             0
dtype: int64

___Question:___ if missing data, describe an scenario where omitting rows would be considered <br>
___Question:___ if missing data, describe how would you handle it if not omitted <br>

In [ ]:
df['education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

__Exercise:__ Create a column named `target` mapping each academic level to a numeric value. Use the the map function over a dictionary `educationnum_dict`.

In [ ]:
educationnum_dict = {
    1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1,
    9: 2,
    10: 3, 11: 3, 12: 3,
    13: 4,
    14: 5,
    15: 6, 16: 6
}

In [ ]:
# YOUR CODE HERE

___Question:___ Is this encoding a linear encoding? <br>
___Commemt:___ Titanic class

In [ ]:
df.groupby(['education'
            ,'educationnum'
           ## , 'target'
           ]).size().reset_index().rename(columns={0:'count'}).sort_values(by=['educationnum']
                                                                                , ascending=False)

       education  educationnum  count
10     Doctorate            16    413
14   Prof-school            15    576
12       Masters            14   1723
9      Bachelors            13   5355
7     Assoc-acdm            12   1067
8      Assoc-voc            11   1382
15  Some-college            10   7291
11       HS-grad             9  10501
2           12th             8    433
1           11th             7   1175
0           10th             6    933
6            9th             5    514
5        7th-8th             4    646
4        5th-6th             3    333
3        1st-4th             2    168
13     Preschool             1     51

__Exercise:__ Create a column named `bin_salary` Dot ir twice, using different methods: <br>
a) using dictionary `over50k_dict` <br>
b) using an `if` condition

In [ ]:
over50k_dict = {'<=50K':0, '>50K':1}

In [ ]:
1+1

[Back to index](#index)
<a id='ini'></a>

__Popular transformation__

## One Hot Encoding transformation

In [ ]:
df.groupby(['occupation']).size().reset_index().rename(columns={0: 'count'}).sort_values(by='count', ascending=False)

           occupation  count
9      Prof-specialty   4140
2        Craft-repair   4099
3     Exec-managerial   4066
0        Adm-clerical   3770
11              Sales   3650
7       Other-service   3295
6   Machine-op-inspct   2002
13   Transport-moving   1597
5   Handlers-cleaners   1370
4     Farming-fishing    994
12       Tech-support    928
10    Protective-serv    649
8     Priv-house-serv    149
1        Armed-Forces      9

__Example: One-Hot Encoding of "occupation" column__

After one-hot encoding:

Each occupation becomes its own binary column (0 = not present, 1 = present)

-----------------------------------------------------------------------------------------
| Prof-specialty | Craft-repair | Exec-managerial | Adm-clerical | Sales |
|----------------|--------------|------------------|--------------|-------|
| 1              | 0            | 0                | 0            | 0     |  <- Prof-specialty
| 0              | 1            | 0                | 0            | 0     |  <- Craft-repair
| 0              | 0            | 1                | 0            | 0     |  <- Exec-managerial
| 0              | 0            | 0                | 1            | 0     |  <- Adm-clerical
| 0              | 0            | 0                | 0            | 1     |  <- Sales
-----------------------------------------------------------------------------------------

Key idea:
- Only ONE column is 1 per row (if using standard one-hot encoding)
- All other columns are 0
- This converts categorical data into numeric format (useful for ML models)

__Exercise:__ Transform `ocupation` column into a one hot encoded set of columns as per the example.

In [ ]:
#YOUR CODE HERE

__Comment:__ AI answers for dummies | OHE is the last resource

[Back to index](#index)
<a id='Brainstorm'></a>

### Brainstorm
Let's say our working dataset is from an online business of tulips:
- What categorical variables would you One-Hot Encode?
- What categrocial variables would you somehow numericaly transform? Explain the transformation.

`invoiceID` - 1M unique values <br>
`colour` - 30 unique colours <br>
`variety` - 30 unique flower types <br>
`city` - 200 unique cities <br>
`client surname` - 1000 unique values <br>
`% disccount` - 10 unique values <br>
`fragance` - 20 unique values <br>

`income` - continuous<br>
`date` - YYYYMMDD

__Exercise:__ Create a new column `income_log`

[Back to index](#index)
<a id='sql'></a>

__SQL like operations__

In [1]:
import pandas as pd
import numpy as np

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5, 6],
    "name": ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank"],
    "city": ["London", "Paris", "Berlin", "Madrid", "Rome", "Lisbon"]
})

agents = pd.DataFrame({
    "agent_id": [10, 20],
    "agent_name": ["Agent Smith", "Agent Johnson"],
    "region": ["North", "South"]
})

orders = pd.DataFrame({
    "order_id": range(1001, 1021),
    "customer_id": [
        1, 1, 2, 2, 3, 3, 3, 4, 4, 5,
        5, 5, 6, 6, 6, 1, 2, 7, 8, 3   # 7 and 8 don't exist → useful for teaching
    ],
    "agent_id": [
        10, 20, 10, 10, 20, 20, 10, 10, 20, 10,
        20, 20, 10, 10, 20, 20, 10, 10, 30, 20  # 30 doesn't exist → teaching case
    ],
    "amount": [
        120, 80, 50, 60, 200, 150, 90, 40, 75, 300,
        220, 180, 130, 170, 160, 110, 95, 210, 400, 85
    ]
})

In [2]:
customers

   customer_id     name    city
0            1    Alice  London
1            2      Bob   Paris
2            3  Charlie  Berlin
3            4    Diana  Madrid
4            5      Eve    Rome
5            6    Frank  Lisbon

In [3]:
agents

   agent_id     agent_name region
0        10    Agent Smith  North
1        20  Agent Johnson  South

In [5]:
orders

    order_id  customer_id  agent_id  amount
0       1001            1        10     120
1       1002            1        20      80
2       1003            2        10      50
3       1004            2        10      60
4       1005            3        20     200
5       1006            3        20     150
6       1007            3        10      90
7       1008            4        10      40
8       1009            4        20      75
9       1010            5        10     300
10      1011            5        20     220
11      1012            5        20     180
12      1013            6        10     130
13      1014            6        10     170
14      1015            6        20     160
15      1016            1        20     110
16      1017            2        10      95
17      1018            7        10     210
18      1019            8        30     400
19      1020            3        20      85

In [6]:
# what orders where performed by which customers?
orders_customers = pd.merge(
    orders,
    customers,
    on="customer_id",
    how="left"
)

orders_customers

    order_id  customer_id  agent_id  amount     name    city
0       1001            1        10     120    Alice  London
1       1002            1        20      80    Alice  London
2       1003            2        10      50      Bob   Paris
3       1004            2        10      60      Bob   Paris
4       1005            3        20     200  Charlie  Berlin
5       1006            3        20     150  Charlie  Berlin
6       1007            3        10      90  Charlie  Berlin
7       1008            4        10      40    Diana  Madrid
8       1009            4        20      75    Diana  Madrid
9       1010            5        10     300      Eve    Rome
10      1011            5        20     220      Eve    Rome
11      1012            5        20     180      Eve    Rome
12      1013            6        10     130    Frank  Lisbon
13      1014            6        10     170    Frank  Lisbon
14      1015            6        20     160    Frank  Lisbon
15      1016            1        20     110    Alice  London
16      1017            2        10      95      Bob   Paris
17      1018            7        10     210      NaN     NaN
18      1019            8        30     400      NaN     NaN
19      1020            3        20      85  Charlie  Berlin

__Exercise:__ what customers were sold by what agents?

In [ ]:
#YOUR ANSWER HERE

__Exercise:__ Who sold the most?

In [ ]:
#YOUR ANSWER HERE